version: '2.15.1'
services:
  postgres:
    image: postgres:14.6
    restart: always
    container_name: postgres
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - progres_data:/data/postgres
    env_file:
      - .env

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - server-side
    env_file:
      - .env

volumes:
  progres_data:

networks:
  server-side:
    driver: bridge